Add shortcut to toggle the left sidebar
Map sidebar toggle to `\m`.

Initialise the code after a timeout to account for Gmail's initial
loading screen.

Needed to use an `as HTMLElement` cast in order to get the code to
compile:
https://github.com/Microsoft/TypeScript/issues/16920

    src/sidebar.ts:10:5 - error TS2740: Type 'Element' is missing the
    following properties from type 'HTMLElement': accessKey,
    accessKeyLabel, autocapitalize, dir, and 110 more.